### ISSUE TITLE
minor documentation issue: formatting problems in some sections of pdf

### ISSUE THREAD

**Issue by adf-ncgr** [NAL-i5K/GFF3toolkit#100]
Hi- 
just looking over https://buildmedia.readthedocs.org/media/pdf/gff3toolkit/latest/gff3toolkit.pdf
I noticed that sections like:
2.1.3 Single feature (Esf)
4.2 gff3_fix
and some others appear to be missing tabular formatting, making them a little difficult to assimilate by the prospective user. Looks like it is likely a case of :
https://stackoverflow.com/questions/44461762/sphinx-is-not-recognising-my-markdown-tables
the md from which I'm guessing it was generated renders quite nicely in 
https://github.com/NAL-i5K/GFF3toolkit/blob/master/docs/gff3_fix.py-documentation.md
so I'm just going to refer to those, but thought I'd mention it anyway since I had stumbled across the pdf first. may not be worth fixing, but https://pypi.org/project/sphinx-markdown-tables/ as mentioned in the SO post may be worth a try?

thanks for a nicely documented set of tools!

**Comment by hsiaoyi0504** [comment]
Just mention the documents that cause this problem for later inspection.

2.1.3 is in https://github.com/NAL-i5K/GFF3toolkit/blob/master/docs/Detection-of-GFF3-format-errors.md

and

4.2 is in https://github.com/NAL-i5K/GFF3toolkit/blob/master/docs/gff3_fix.py-documentation.md

**Comment by mpoelchau** [comment]
Thanks for the pointers @adf-ncgr and @hsiaoyi0504 ! I'll try to get to this next week.

**Comment by mpoelchau** [comment]
I cheated and just changed the offending docs to rst. Should be fixed in #102. Thanks all!
