### ISSUE TITLE
Pip install 

### ISSUE THREAD

**Issue by OscarChou211** [NAL-i5K/GFF3toolkit#104]
Hi there, 

Thank you very much for helping! 

I am trying to use the GFF3toolkit in my MacOS, installing using pip install. I wonder what is the reason for that? Thank you very much for helping! 

The following are my errors: 

apple@pc-206-171 ~ % python3 -m pip install git+https://github.com/NAL-i5K/GFF3toolkit.git 
Collecting git+https://github.com/NAL-i5K/GFF3toolkit.git
  Cloning https://github.com/NAL-i5K/GFF3toolkit.git to /private/var/folders/c_/qk6ctf6513q1ygygbvsw15880000gn/T/pip-req-build-wynu3ymp
  Running command git clone -q https://github.com/NAL-i5K/GFF3toolkit.git /private/var/folders/c_/qk6ctf6513q1ygygbvsw15880000gn/T/pip-req-build-wynu3ymp
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/c_/qk6ctf6513q1ygygbvsw15880000gn/T/pip-req-build-wynu3ymp/setup.py'"'"'; __file__='"'"'/private/var/folders/c_/qk6ctf6513q1ygygbvsw15880000gn/T/pip-req-build-wynu3ymp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/c_/qk6ctf6513q1ygygbvsw15880000gn/T/pip-pip-egg-info-sbqce5fp
         cwd: /private/var/folders/c_/qk6ctf6513q1ygygbvsw15880000gn/T/pip-req-build-wynu3ymp/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/c_/qk6ctf6513q1ygygbvsw15880000gn/T/pip-req-build-wynu3ymp/setup.py", line 22, in <module>
        from wheel.bdist_wheel import bdist_wheel as _bdist_wheel
    ModuleNotFoundError: No module named 'wheel'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by ShangYuChiang** [comment]
Sorry to hear about the mishap, it looks like your python environment didn't have the `wheel` module
I suggest you could make sure that wheel is installed
`pip install wheel` 
*Support is offered in pip >= 1.4 and setuptools >= 0.8.
so you could also install it explicitly yourself, together with setuptools:
`python -m pip install wheel setuptools`

if there still has the error about  setup.py egg_info after `wheel` was installed.
you could try the following commit:
Please update setup tools `pip install -U setuptools` 
or `sudo pip3 install --upgrade pip setuptools wheel`

Thanks for using i5k GFF3toolkits.

**Comment by mpoelchau** [comment]
Hi @OscarChou211 - just checking, were you able to install using @ShangYuChiang's advice? 

If so, we can close the issue.

**Comment by OscarChou211** [comment]
Hi there, it helped indeed. The problem is solved! Thank you very much for helping!
