### ISSUE TITLE
gff3_fix error

### ISSUE THREAD

**Issue by yemao701** [NAL-i5K/GFF3toolkit#107]
Thanks you for your wonderful tool kit! 
When I run gff3_fix follow your instruction, I encountered a error:
![QQ截图20200804004653](https://user-images.githubusercontent.com/63441746/89206659-2c45ee00-d5ec-11ea-90c9-bad08b3fb72e.jpg)
This is the error report generated by gff3_QC:
![QQ截图20200804004741](https://user-images.githubusercontent.com/63441746/89206703-3d8efa80-d5ec-11ea-8b16-060cf4483951.jpg)
This is my gff file:

[Finalv2.rep.genename.v2.nored.zip](https://github.com/NAL-i5K/GFF3toolkit/files/5017192/Finalv2.rep.genename.v2.nored.zip)

Can you help me fix this problem?

**Comment by mpoelchau** [comment]
@yemao701 sorry about the issues. gff3_fix expects ID attributes for all features. I'll update the FAQ and readme with this information. You can use the gff3_ID_generator.py script in the `lib` directory to generate IDs. 

`python lib/gff3_ID_generator.py -g in.gff3 -og out.gff -uuid -r report.txt`

**Comment by yemao701** [comment]
> @yemao701 sorry about the issues. gff3_fix expects ID attributes for all features. I'll update the FAQ and readme with this information. You can use the gff3_ID_generator.py script in the `lib` directory to generate IDs.
> 
> `python lib/gff3_ID_generator.py -g in.gff3 -og out.gff -uuid -r report.txt`

Thank you for your timely response.

**Comment by yemao701** [comment]
@mpoelchau  Sorry to bother you again, when I run lib/gff3_ID_generator.py I got this error.
![QQ截图20200805144408](https://user-images.githubusercontent.com/63441746/89380590-57cef280-d72a-11ea-9a09-e1138eb9e06a.jpg)
I install gfftools through pip3 install.

**Comment by hsiaoyi0504** [comment]
@yemao701 Based on what I saw in your screenshot, I would guess that you have used two different python virtual environments at the same time.

**Comment by mpoelchau** [comment]
I agree with @hsiaoyi0504 that there's an issue with your python virtual environment. 

If you do `pip3 list`, is gff3tool one of the listed modules? 

What python version are you using (`python -V`)?

**Comment by yemao701** [comment]
@mpoelchau  @hsiaoyi0504  I think taht gff3tools was properly installed by pip3 and the python version is 3.7.4
![QQ截图20200806140352](https://user-images.githubusercontent.com/63441746/89496860-b610d980-d7ed-11ea-8215-6677987bf141.jpg)

**Comment by mpoelchau** [comment]
@yemao701 I issued an update that will hopefully fix your problem - can you pull again from the master branch?

**Comment by mpoelchau** [comment]
Great, I am glad that you got it working!
