### ISSUE TITLE
Anaconda have something wrong when runing example script

### ISSUE THREAD

**Issue by Ravenclawer** [NAL-i5K/GFF3toolkit#113]
I have used conda to deploy gff_fix tools and tried to learn the workflow with example project but something went wrong：
![image](https://user-images.githubusercontent.com/73892411/132223759-e2680ec4-9ea4-4e9b-bd4b-5e76b6c398c8.png)

**Comment by debbiedai** [comment]
Hi, @Ravenclawer 
Have you install Perl ? If you run the command on Windows, you might need to install Perl first.

**Comment by Ravenclawer** [comment]
Thank you very much for replying, I have tried to run it in vmware but it didn't work, then I came back to install strawberry perl and it worked！
