### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by papelypluma** [NAL-i5K/GFF3toolkit#117]
Hi GFF3toolkit developers. I'd like to seek for your help on this issue. QC part went well, but running the fix step raises a ValueError exception. For reference, I'm attaching the gff file and the error.txt here.

[gff3_files.zip](https://github.com/NAL-i5K/GFF3toolkit/files/7356596/gff3_files.zip)

Thank you.

**Comment by mpoelchau** [comment]
Hi @papelypluma - it looks like the models in your gff3 file are not formatted in the 'canonical' style (see https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md). I'd recommend using the `-noncg` flag when running gff3_QC.
