### ISSUE TITLE
gff3_fix error

### ISSUE THREAD

**Issue by elor77** [NAL-i5K/GFF3toolkit#118]
I ran gff3_QC with no problems. 
When I run gff3_fix i get the following error:
```DUL-latest]$ gff3_fix -qc_r error.txt -g DUL_02_latest_Melon_V4_liftoff.gff -og DUL_02_latest_Melon_V4_liftoff.corrected.gff
INFO     Checking QC report file (error.txt)...
INFO     Checking GFF3 file (DUL_02_latest_Melon_V4_liftoff.gff)...
INFO     Reading QC report file: (error.txt)...

INFO     Reading GFF3 file: (DUL_02_latest_Melon_V4_liftoff.gff)...

Traceback (most recent call last):
  File "/home/eoren/miniconda3/bin/gff3_fix", line 8, in <module>
    sys.exit(script_main())
  File "/home/eoren/miniconda3/lib/python3.9/site-packages/gff3tool/bin/gff3_fix.py", line 95, in script_main
    gff3_fix.fix.main(gff3=gff3, output_gff=args.output_gff, error_dict=error_dict, line_num_dict=line_num_dict, logger=logger_null)
  File "/home/eoren/miniconda3/lib/python3.9/site-packages/gff3tool/lib/gff3_fix/fix.py", line 683, in main
    fix_phase(gff3=gff3, error_list=error_dict[error_code], line_num_dict=line_num_dict, logger=logger)
  File "/home/eoren/miniconda3/lib/python3.9/site-packages/gff3tool/lib/gff3_fix/fix.py", line 437, in fix_phase
    phase = (3 - ((CDS['end'] - CDS['start'] + 1 - phase) % 3)) % 3
TypeError: unsupported operand type(s) for -: 'int' and 'str'
```

**Comment by elor77** [comment]
Hi @ZhiXuanLai  
Sure, here you go. This is a gff file created with https://github.com/agshumate/Liftoff

[DUL_pseudomol_v1.0_Melon_V4_liftoff.gff.gz](https://github.com/NAL-i5K/GFF3toolkit/files/7444499/DUL_pseudomol_v1.0_Melon_V4_liftoff.gff.gz)
[error.txt.gz](https://github.com/NAL-i5K/GFF3toolkit/files/7444501/error.txt.gz)

**Comment by mpoelchau** [comment]
@elor77 thanks for posting this issue. We are still trying to figure out the problem. In the meantime, I'd recommend following the solution posted here: https://github.com/agshumate/Liftoff/issues/67#issuecomment-804528269

**Comment by mpoelchau** [comment]
@elor77 apologies that I didn't follow up on this. The latest version of the gff3toolkit should handle this problem. https://github.com/NAL-i5K/GFF3toolkit/releases/tag/v2.1.0

**Comment by elor77** [comment]
Thank you!
