### ISSUE TITLE
Extract protein seq 

### ISSUE THREAD

**Issue by bsb2014** [NAL-i5K/GFF3toolkit#131]
Thanks for developing this tool.  May I know how gff3_to_fasta handles iupac bases in the genome fasta for translation?

**Comment by mpoelchau** [comment]
Hi @bsb2014 - The code for handling iupac bases in protein translation is here: https://github.com/NAL-i5K/GFF3toolkit/blob/9b36c5cbc90f3fb51fb91cac581b18a3c58630b5/gff3tool/bin/gff3_to_fasta.py#L57

Basically, we build an array of all possible codon combinations of ATGC in line 56; then add all known codons with iupac bases to that array in line 57. Line 58 defines an array with the amino acid symbols (in matched order to the array of codons), then line 59 combines the 2 arrays into a dictionary.

Hth, let us know if you have any questions!

**Comment by bsb2014** [comment]
Is it possible to add a function to translate codons with iupac bases to "-"? Thanks

**Comment by mpoelchau** [comment]
Do you mean IUPAC symbols that code for multiple bases (e.g. R stands for G or A)? Unfortunately we don't have capacity to develop new features for this package. Perhaps you could change symbols that code for multiple bases to N's in your nucleotide sequence, if you have valid reasons to do this. I wouldn't change the nucleotide sequence or protein translation without a really good reason, though.

**Comment by bsb2014** [comment]
As for my case, the IUPAC bases (e.g. R) in the fasta means sequencing errors or heterozygous regions. I would like to label the amino acids if they were translated from these IUPAC bases. Thanks
