### ISSUE TITLE
No module named 'gff3tool'

### ISSUE THREAD

**Issue by emilpaulitz** [NAL-i5K/GFF3toolkit#138]
Hi team, 

I want to merge multiple gff files using gff3_merge. However, I have trouble with the install as described in the github Readme. I create a fresh environment with the stated prerequisites python and perl (python is installed with version 3.12.4, wheel is also installed), and then install gff3tool with pip:

```
mamba create -n gff3tools python perl
pip install gff3tool
```

However, when I call gff3_merge with any or no arguments, I immediately receive the error 

```
Traceback (most recent call last):
  File "~/.local/bin/gff3_merge", line 6, in <module>
    from gff3tool.bin.gff3_merge import script_main
ModuleNotFoundError: No module named 'gff3tool'
```

Any ideas what could be the issue?

**Comment by emilpaulitz** [comment]
Solved it. My mamba version is installed locally, while conda is managed server-wide. Somehow the mamba environment did not work for gff3_tools. Calling `conda deactivate` until nothing changed anymore, and reinstalling everything with conda instead of mamba worked. Probably a very specific situation.

**Comment by mpoelchau** [comment]
I'm glad you figured that out @emilpaulitz! Thanks for the update. 

I'm going to close the issue, but feel free to reopen it if anything related pops up.
