### ISSUE TITLE
gff3 merge error

### ISSUE THREAD

**Issue by beantkapoor786** [NAL-i5K/GFF3toolkit#140]
Hello, I have run gff3_QC and gff3_fix on my two gff files but I am getting the following error while using the gff3_merge command
```
gff3_merge -g1 Qalba_4.3.1.HapA.genes_corrected.gff3 -g2 QalbaA_NBARC_corrected.gff3 -f Qalba_4.3.0.HapA.fasta -og Qalba_4.3.1_Braker_FindPlantNLR_merged.gff3 -r Qalba_4.3.1_Braker_FindPlantNLR_merged_report.txt --all
```
Error -
```
Traceback (most recent call last):
  File "/nfs/home/bkapoor/miniforge3/bin/gff3_merge", line 8, in <module>
    sys.exit(script_main())
             ^^^^^^^^^^^^^
  File "/nfs/home/bkapoor/miniforge3/lib/python3.12/site-packages/gff3tool/bin/gff3_merge.py", line 229, in script_main
    main(args.gff_file1, args.gff_file2, args.fasta, report_fh, args.output_gff, args.all, args.auto_assignment, args.user_defined_file1, args.user_defined_file2, logger=logger_stderr)
  File "/nfs/home/bkapoor/miniforge3/lib/python3.12/site-packages/gff3tool/bin/gff3_merge.py", line 85, in main
    gff3_merge.merge.main(autoReviseGff, gff_file2, output_gff, report, user_defined1, user_defined2, logger)
  File "/nfs/home/bkapoor/miniforge3/lib/python3.12/site-packages/gff3tool/lib/gff3_merge/merge.py", line 120, in main
    ans = ReplaceGroups.replacer_multi(root, ReplaceGroups, gff3M, u1_types, u2_types)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfs/home/bkapoor/miniforge3/lib/python3.12/site-packages/gff3tool/lib/replace_OGS.py", line 907, in replacer_multi
    self.info.append('{0:s}\t{1:s}\t{2}\t{3:s}'.format(originalID, newtarget['attributes']['ID'], newtarget['attributes']['replace'], newtarget['attributes']['modified_track']))
                                                                                                  ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'replace'
```
My python version is 3.12.7. Please let me know if you have any suggestions. Thank you!

**Comment by mpoelchau** [comment]
Hi @beantkapoor786. Sorry you're having trouble with the gff3_merge program. Could you send me a snippet of your gff3 file, and let me know what attributes are in column 9? Thanks!

**Comment by beantkapoor786** [comment]
For sure, I have attached two gff3 files in text format each containing first 1,000 lines of annotated gene models. We have `ID` and `Parent` attributes in column 9.

[Qalba_4.3.1.HapA.genes_corrected_snippet.txt](https://github.com/user-attachments/files/17821834/Qalba_4.3.1.HapA.genes_corrected_snippet.txt)
[QalbaA_NBARC_corrected_snippet.txt](https://github.com/user-attachments/files/17821835/QalbaA_NBARC_corrected_snippet.txt)

Please let me know if you need anything else. Thank you.

**Comment by MonicaPoelchau-USDA** [comment]
Can you try removing all stop_codon, start_codon and intron features so that the gffs only have gene, mRNA, CDS and exon features? I'm not sure if this is the problem, but it's worth a try.

**Comment by beantkapoor786** [comment]
I tried that and it still gives the same error

**Comment by MonicaPoelchau-USDA** [comment]
I am not sure what's going on, apologies. I downloaded the Quercus alba haplotype 1 assembly from NCBI and swapped out chromosome ids in the gffs you sent to match for a quick test. The merge program completed for me, although 1) I did get a missing attributes warning, and 2) I used python 3.11.1. I ran our ancillary script to change IDs on one of the gff3 files, and that got rid of the warning. Perhaps you can try this as well on your files.  

`python GFF3toolkit/gff3tool/lib/gff3_ID_generator.py -g QalbaA_NBARC_corrected_snippet.txt -og QalbaA_NBARC_corrected_snippet-newids.gff -uuid -r idreport.txt -a`

**Comment by beantkapoor786** [comment]
It seems like that problem was we had identical gene IDs between two gff3 files. When I replaced the gene IDs in one of the gff3 files, it worked. Thank you.
