### ISSUE TITLE
Fix document on readthedocs

### ISSUE THREAD

**Issue by hsiaoyi0504** [NAL-i5K/GFF3toolkit#73]
Related to sphinx-doc/sphinx#5490

**Comment by hsiaoyi0504** [comment]
1.8.2 was released three days ago https://github.com/sphinx-doc/sphinx/releases/tag/v1.8.2. After rebuilding all the documents, it works now.

**Comment by mpoelchau** [comment]
Thank you @hsiaoyi0504!
