### ISSUE TITLE
error with gff3_sort: missing SeqID

### ISSUE THREAD

**Issue by lassancejm** [NAL-i5K/GFF3toolkit#85]
Hi, 

I am experiencing the following error with gff3_sort:

`ERROR  [Missing SeqID] Missing SeqID.
		- Line 2246892: chrX	CAT	gene	44080	557481	.	-	.	ID=OLDFIELD_G0043730;Name=Aff2;source_gene_common_name=Aff2;source_gene=ENSMUSG00000031189.12;transcript_modes=transMap;gene_biotype=protein_coding`

As the line is not missing anything as far as I can tell, it seems that the error is caused by the naming of the seqID ("chrX").

**Comment by mpoelchau** [comment]
Hi @lassancejm - does your fasta file contain a sequence with the ID chrX in the defline?

**Comment by lassancejm** [comment]
yes, chrX is present in the fasta file.

A simple fix was to change "X" into an arbitrary numerical value and then the command runs.

**Comment by mpoelchau** [comment]
Really! That would be a bug. Thanks for the report; we'll look into this.

**Comment by mpoelchau** [comment]
@tony006469 can you add a new argument 'seqid-sort' to gff3_sort that will sort the gff3 by the number of the reference sequence (the current behavior)? If 'reference-sort' is not passed, then the program should use the pre-existing scaffold order for sorting.

**Comment by tony006469** [comment]
@mpoelchau  
https://github.com/NAL-i5K/GFF3toolkit/tree/new_argument_for_seqid_no_number
It's ready for testing.

**Comment by tony006469** [comment]
![error.png](https://images.zenhubusercontent.com/5bc4a57039f03821ed48e81f/c170bc9d-65bd-4233-a425-fbd9dbc68a36)

Should I run the new test6 file through the gff-QC program first?

**Comment by tony006469** [comment]
Command: gff3_sort -g /home/tony/Desktop/sort_testfiles/test2.gff -og example-sorted.gff3 -r

![1.png](https://images.zenhubusercontent.com/5bc4a57039f03821ed48e81f/6c41a6a9-ef8a-4b8b-86a1-e905a6ba022c)

![2.png](https://images.zenhubusercontent.com/5bc4a57039f03821ed48e81f/fcb8ca4a-bc6c-4fe3-87f6-a17ba1e9f9c4)

![3.png](https://images.zenhubusercontent.com/5bc4a57039f03821ed48e81f/dbeeb7fc-5195-46f5-8b6e-11178061eb60)

**Comment by mpoelchau** [comment]
Fixed via #87. Thanks for reporting @lassancejm. Closing this - feel free to reopen if you notice any problems.
