### ISSUE TITLE
refactor to make unit testing easier

### ISSUE THREAD

**Issue by childers** [NAL-i5K/GFF3toolkit#88]
Should we refactor this to make unit testing easier? 
Was looking at how to implement test coverage and add unit tests.
We have 40 repositories in the NAL_i5k org.

- [ ] Genomics Workspace https://github.com/NAL-i5K/genomics-workspace
- [ ] GFF3Toolkit https://github.com/NAL-i5K/GFF3toolkit
- [ ] NAL_CSS https://github.com/NAL-i5K/NAL_CSS
- [ ] wiggle-tools https://github.com/NAL-i5K/wiggle-tools
- [ ] github_stat https://github.com/NAL-i5K/github_stat
- [ ] retrieve_assembly_metadata https://github.com/NAL-i5K/retrieve_assembly_metadata
- [ ]

**Comment by hsiaoyi0504** [comment]
@childers should we move this issue into general_issues repo ?

**Comment by childers** [comment]
@hsiaoyi0504 Yes! This definitely should go into general_issues.  Thanks for catching it!

**Comment by childers** [comment]
Moved to https://github.com/NAL-i5K/general_issues/issues/66
