### ISSUE TITLE
Convert to python3

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/GFF3toolkit#94]
- [x] review branch python3.6
- [x] review PyPi setup
- [x] Make a new python2.7 release based on current master 
- [x] Merge python3.6 into master
- [x] make new python3 release

**Comment by ShangYuChiang** [comment]
Revise the GFF3toolkit to Python3. 
bin
- [] gff3_fix.py
- [] gff3_merge.py
- [] gff3_QC.py
- [] gff3_sort.py
- [] gff3_to_fasta.py
lib
- [] ERROR\ERROR.py
- [] function4gff\function4gff.py
- [] gff3\gff3.py
- [] gff3_fix\fix.py
- [] gff3_merge\auto_replace_tag.py
- [] gff3_merge\merge.py
- [] gff3_merge\revision.py
- [] inter_model\inter_model.py
- [] intra_model\intra_model.py
- [] single_feature\single_feature.py
- [] gff3_ID_generator .py
- [] id_processor.py
- [] replace_OGS.py
- [] utils.py
- [] .travis.yml
